from fpdf import FPDF
import matplotlib.pyplot as plt
import os
from datetime import datetime

class VerdictReport(FPDF):
    def header(self):
        # Логотип и Заголовок
        self.set_font('Courier', 'B', 20)
        self.cell(0, 10, 'MAGNUM OPS // FORENSIC LAB', 0, 1, 'L')
        self.set_font('Courier', '', 10)
        self.cell(0, 5, 'Algorithmic Trading Stress-Testing Unit', 0, 1, 'L')
        self.line(10, 25, 200, 25) # Линия во всю ширину
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font('Courier', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'CONFIDENTIAL // Page {self.page_no()} // Generated by MAGNUM-v0.2', 0, 0, 'C')

    def section_title(self, label):
        self.set_font('Courier', 'B', 14)
        self.set_fill_color(230, 230, 230) # Серый фон
        self.set_text_color(0)
        self.cell(0, 8, f" {label}", 0, 1, 'L', fill=True)
        self.ln(4)

    def body_text(self, text):
        self.set_font('Courier', '', 11)
        self.multi_cell(0, 5, text)
        self.ln(5)

class Reporter:
    def __init__(self, output_dir="/data/reports"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def generate_chart(self, trades_df, death_trade, filename):
        """Рисует красивый график"""
        plt.figure(figsize=(10, 4))
        # Стиль графика
        plt.style.use('ggplot')
        
        # Цена
        plt.plot(trades_df['timestamp'], trades_df['price'], color='#333333', linewidth=1.5, label='Price Action')
        
        # Точка смерти
        death_time = death_trade['timestamp']
        death_price = death_trade['price']
        plt.scatter([death_time], [death_price], color='red', s=150, marker='x', zorder=5, label='LIQUIDATION EVENT')
        
        plt.title(f"Asset: {death_trade['symbol']} | Timeframe: M1", fontsize=10)
        plt.xlabel("")
        plt.ylabel("Price (USDT)")
        plt.legend()
        plt.tight_layout()
        
        chart_path = os.path.join(self.output_dir, filename)
        plt.savefig(chart_path, dpi=100)
        plt.close()
        return chart_path

    def create_verdict(self, case_id, trade_data, z3_result, historical_df):
        pdf = VerdictReport()
        pdf.add_page()
        
        # --- 1. CASE OVERVIEW ---
        pdf.section_title("1. CASE OVERVIEW")
        
        pdf.set_font("Courier", size=11)
        pdf.cell(40, 8, "CASE ID:", 0, 0)
        pdf.set_font("Courier", 'B', 11)
        pdf.cell(0, 8, case_id, 0, 1)
        
        pdf.set_font("Courier", size=11)
        pdf.cell(40, 8, "DATE:", 0, 0)
        pdf.cell(0, 8, datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC'), 0, 1)
        
        pdf.cell(40, 8, "SYMBOL:", 0, 0)
        pdf.cell(0, 8, f"{trade_data['symbol']} ({trade_data['side']})", 0, 1)
        
        pdf.cell(40, 8, "EXEC PRICE:", 0, 0)
        pdf.set_text_color(200, 0, 0) # Red
        pdf.cell(0, 8, f"{trade_data['price']}", 0, 1)
        pdf.set_text_color(0)
        pdf.ln(5)

        # --- 2. FORENSIC VERDICT ---
        pdf.section_title("2. FORENSIC VERDICT")
        
        verdict = z3_result.get('verdict', 'UNKNOWN')
        
        if verdict == 'LIQUIDITY_VOID_DETECTED':
            status = "CRITICAL FAILURE DETECTED"
            color = (255, 0, 0) # Red
        else:
            status = "CLEAN EXECUTION"
            color = (0, 128, 0) # Green
            
        pdf.set_font("Courier", 'B', 16)
        pdf.set_text_color(*color)
        pdf.cell(0, 10, f"[{verdict}]", 0, 1, 'C')
        pdf.set_font("Courier", 'B', 12)
        pdf.cell(0, 8, status, 0, 1, 'C')
        pdf.set_text_color(0)
        pdf.ln(5)

        # --- 3. EVIDENCE (CHART) ---
        pdf.section_title("3. VISUAL EVIDENCE")
        if not historical_df.empty:
            chart_file = f"chart_{case_id}.png"
            chart_path = self.generate_chart(historical_df, trade_data, chart_file)
            # Центрируем картинку
            pdf.image(chart_path, x=10, w=190)
            pdf.ln(5)

        # --- 4. MATHEMATICAL PROOF (Z3) ---
        pdf.section_title("4. FORMAL VERIFICATION (Z3 SOLVER)")
        
        proof_text = """
        Magnum Ops uses Formal Verification methods to audit execution quality. 
        Unlike probabilistic backtests, we utilize the Microsoft Z3 Theorem Prover 
        to construct a logical proof of market conditions.
        
        LOGIC CONSTRAINT:
        Abs(ExecPrice - MarketPrice) <= Spread + Slippage Tolerance
        
        SOLVER OUTPUT:
        """
        pdf.body_text(proof_text)
        
        # Вывод Z3 в рамке
        pdf.set_font("Courier", '', 10)
        pdf.set_fill_color(240, 240, 240)
        details = z3_result.get('details', 'No details.')
        pdf.multi_cell(0, 5, details, border=1, fill=True)
        pdf.ln(10)

        # --- 5. CERTIFICATION ---
        pdf.section_title("5. CERTIFICATION")
        cert_text = """
        This document certifies that the trade event has been mathematically analyzed 
        against historical tick data. The result serves as a cryptographic proof 
        of the strategy's performance under stress conditions.
        
        Trustless Auditing Engine: v0.2.0
        """
        pdf.body_text(cert_text)

        # Сохранение
        filename = f"VERDICT_{case_id}.pdf"
        filepath = os.path.join(self.output_dir, filename)
        pdf.output(filepath)
        print(f"[Reporter] PDF Generated: {filepath}")
        return filepath
